import type { VehicleInfo } from "@/lib/types/chat";

export type ShopReportSource = "chat" | "coach";

export type ShopReportDtc = {
  code: string;
  /** Local SAE-style title — not a root-cause assertion. */
  definition: string;
  severity?: string;
  catalogHit?: boolean;
};

export type ShopReportRecallHint = {
  campaignNumber: string;
  component: string;
  summary: string;
};

/** US NHTSA education block (max 3 campaigns). Omit for non-US / fetch skip. */
export type ShopReportRecallEducation = {
  source: "nhtsa-recalls";
  ymm: string;
  lookupUrl: string;
  footnote: string;
  status: "listed" | "empty" | "unavailable";
  total: number;
  hints: ShopReportRecallHint[];
};

export type ShopReportFactor = {
  title: string;
  explanation: string;
  howToVerify: string;
};

export type ShopReportPayload = {
  reportId: string;
  generatedAtIso: string;
  source: ShopReportSource;
  vehicle: {
    year: number;
    make: string;
    model: string;
    submodel?: string;
    mileage?: number;
    vinLast8?: string | null;
    vinFull?: string | null;
    plate?: string | null;
  };
  ownerObservations: {
    symptoms: string;
    conditions: string;
    checksDone: string[];
  };
  diagnosticData: {
    codes: ShopReportDtc[];
    liveDataSummary: string | null;
    dataSourceNote: string | null;
    /** Present when codes were listed — education, not a diagnosis. */
    codeNote?: string | null;
  };
  /** US vehicles only when NHTSA was requested (fail-open if fetch missed). */
  recallEducation?: ShopReportRecallEducation | null;
  contributingFactors: ShopReportFactor[];
  checksCompleted: string[];
  technicianNextSteps: string[];
  ownerNotes: string | null;
  disclaimer: string;
  /** Optional compressed diagnostic screenshots (data URLs) */
  images?: string[];
};

export type ShopReportGenerateOptions = {
  includeFullVin: boolean;
  includeImages: boolean;
  includeInventory: boolean;
  ownerNotes: string;
  /** US default on — attach NHTSA education (max 3). Non-US ignored. */
  includeRecalls?: boolean;
};

export type ShopReportPreview = {
  ymm: string;
  mileageLabel: string;
  symptomPreview: string;
  codes: string[];
  hasEnoughData: boolean;
  reasonIfEmpty?: string;
};

export type ShopReportChatMessage = {
  role: "user" | "assistant";
  content: string;
  image?: string;
  images?: string[];
  /** Kimi perception codes from this turn, if any. */
  imageAnalysis?: { dtc_codes?: string[] } | null;
};

export type ShopReportGenerateRequest = {
  source: ShopReportSource;
  vehicle: VehicleInfo;
  messages?: ShopReportChatMessage[];
  /** Pre-compressed screenshots from the client (max 3) */
  images?: string[];
  /** Coach completion / last-step text when source=coach */
  coachContext?: {
    scenarioTitle: string;
    scenarioSlug?: string;
    completionText: string;
    lastStepText?: string;
  };
  options: ShopReportGenerateOptions;
};

export type ShopReportListItem = {
  id: string;
  reportCode: string;
  source: ShopReportSource;
  createdAt: string;
  expiresAt: string | null;
  publicToken: string | null;
  codes: string[];
  status: "active" | "expired";
  publicUrl: string | null;
};

export const SHOP_REPORT_DISCLAIMER =
  "This report is generated by Garage Genius AI based on owner-provided information and available diagnostic data. It is intended solely to assist communication with a qualified technician and does NOT constitute a professional diagnosis or repair recommendation. Always have a certified technician verify findings before any repair work. Garage Genius AI assumes no liability for repair decisions or outcomes. This report does not advise on insurance coverage and is not proof of proper repair. Repair and coverage decisions remain between you, your technician, and your insurer.";

export const SHOP_REPORT_DTC_NOTE =
  "Fault codes and titles come from a local SAE-style catalog for communication with a technician. They are not a root-cause diagnosis and do not mean a part must be replaced.";

export const SHOP_REPORT_RECALL_MAX = 3;
