import type { VehicleInfo } from "@/lib/types/chat";

export type ShopReportSource = "chat" | "coach";

export type ShopReportDtc = {
  code: string;
  definition: string;
  severity?: string;
};

export type ShopReportFactor = {
  title: string;
  explanation: string;
  howToVerify: string;
};

export type ShopReportPayload = {
  reportId: string;
  generatedAtIso: string;
  source: ShopReportSource;
  vehicle: {
    year: number;
    make: string;
    model: string;
    submodel?: string;
    mileage?: number;
    vinLast8?: string | null;
    vinFull?: string | null;
    plate?: string | null;
  };
  ownerObservations: {
    symptoms: string;
    conditions: string;
    checksDone: string[];
  };
  diagnosticData: {
    codes: ShopReportDtc[];
    liveDataSummary: string | null;
    dataSourceNote: string | null;
  };
  contributingFactors: ShopReportFactor[];
  checksCompleted: string[];
  technicianNextSteps: string[];
  ownerNotes: string | null;
  disclaimer: string;
};

export type ShopReportGenerateOptions = {
  includeFullVin: boolean;
  includeImages: boolean;
  includeInventory: boolean;
  ownerNotes: string;
};

export type ShopReportPreview = {
  ymm: string;
  mileageLabel: string;
  symptomPreview: string;
  codes: string[];
  hasEnoughData: boolean;
  reasonIfEmpty?: string;
};

export type ShopReportChatMessage = {
  role: "user" | "assistant";
  content: string;
  image?: string;
  images?: string[];
};

export type ShopReportGenerateRequest = {
  source: ShopReportSource;
  vehicle: VehicleInfo;
  messages?: ShopReportChatMessage[];
  /** Coach completion / last-step text when source=coach */
  coachContext?: {
    scenarioTitle: string;
    scenarioSlug?: string;
    completionText: string;
    lastStepText?: string;
  };
  options: ShopReportGenerateOptions;
};

export const SHOP_REPORT_DISCLAIMER =
  "This report is generated by Garage Genius AI based on owner-provided information and available diagnostic data. It is intended solely to assist communication with a qualified technician and does NOT constitute a professional diagnosis or repair recommendation. Always have a certified technician verify findings before any repair work. Garage Genius AI assumes no liability for repair decisions or outcomes.";
